version: '3.8'

services:
  # Main application - just add your .env file and run!
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - DATABASE_URL=sqlite:///./data/conversations.db
    env_file:
      - .env
    volumes:
      - ./data:/app/data  # Database persistence
    restart: unless-stopped

  # Optional services (uncomment if needed for production)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379" 
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

volumes:
  redis_data: