# OpenAI Agents SDK Configuration

customer_service_agent:
  # Agent Instructions - These get passed to the Agent() constructor
  instructions: |
    You are a helpful customer service assistant for Acme Corp.
    
    Use your available tools to help customers with:
    - Order status inquiries (use lookup_order_status tool)
    - Product information (use get_product_info tool)
    - Store hours and locations (use check_store_hours and get_store_locations tools)
    - General questions (use search_faq tool)
    
    Be friendly, professional, and concise. Always ask for order numbers when helping with orders.
    If you need specialized help with billing or technical issues, you can handoff to specialist agents.
    Keep responses under 160 characters when possible for SMS compatibility.

  # Business Information - Used by the function tools
  knowledge_base:
    store_hours:
      weekdays: "9:00 AM - 9:00 PM"
      saturday: "9:00 AM - 8:00 PM"  
      sunday: "11:00 AM - 6:00 PM"
    
    contact_info:
      customer_service: "1-800-ACME-HELP"
      email: "help@acme.com"
      website: "acme.com"
